/**
 * Unix (Linux/macOS) 安装脚本模板
 * 生成用于安装 CRUSH 及其配置的 bash 脚本
 */

/**
 * 生成 Unix 安装脚本
 * @param baseUrl - 配置服务器的基础 URL
 * @returns 完整的 bash 安装脚本
 */
export function generateUnixScript(baseUrl: string): string {
  return `#!/bin/bash
# ============================================================================
# CRUSH Configuration Installer for Unix (Linux/macOS)
# Generated by ${baseUrl}
# ============================================================================

set -e

# ----------------------------------------------------------------------------
# Color Definitions
# ----------------------------------------------------------------------------
RED='\\033[0;31m'
GREEN='\\033[0;32m'
BLUE='\\033[0;34m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
BASE_URL="${baseUrl}"
CONFIG_DIR="\$HOME/.config/crush"
CONFIG_FILE="\$CONFIG_DIR/crush.json"
SKILLS_DIR="\$CONFIG_DIR/skills"
SKILLS_REPO="https://github.com/anthropics/skills.git"
DOCS_URL="${baseUrl}"
INSTALL_DIR="\$HOME/.local/bin"

# ----------------------------------------------------------------------------
# Output Functions
# ----------------------------------------------------------------------------
print_success() {
    echo -e "\${GREEN}✓ \$1\${NC}"
}

print_error() {
    echo -e "\${RED}✗ \$1\${NC}" >&2
}

print_info() {
    echo -e "\${BLUE}ℹ \$1\${NC}"
}

print_warning() {
    echo -e "\${YELLOW}⚠ \$1\${NC}"
}

print_header() {
    echo ""
    echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
    echo -e "\${BLUE}  \$1\${NC}"
    echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
    echo ""
}

# ----------------------------------------------------------------------------
# Error Handler
# ----------------------------------------------------------------------------
error_exit() {
    print_error "\$1"
    exit 1
}

# ----------------------------------------------------------------------------
# Platform Detection
# ----------------------------------------------------------------------------
detect_platform() {
    local os arch
    
    # Detect OS
    case "\$(uname -s)" in
        Linux*)  os="linux";;
        Darwin*) os="darwin";;
        *)       error_exit "Unsupported operating system: \$(uname -s)";;
    esac
    
    # Detect architecture
    case "\$(uname -m)" in
        x86_64|amd64)  arch="amd64";;
        arm64|aarch64) arch="arm64";;
        *)             error_exit "Unsupported architecture: \$(uname -m)";;
    esac
    
    echo "\$os/\$arch"
}

# ----------------------------------------------------------------------------
# Install Crush Binary
# ----------------------------------------------------------------------------
install_crush() {
    local platform="\$1"
    # 直接使用静态文件路径，避免 API 重定向问题
    local os=\$(echo "\$platform" | cut -d'/' -f1)
    local arch=\$(echo "\$platform" | cut -d'/' -f2)
    local download_url="\$BASE_URL/binaries/\$os/\$arch/crush"
    local temp_file="/tmp/crush_binary_\$\$"
    
    print_info "Downloading Crush binary for \$platform..."
    print_info "URL: \$download_url"
    
    # Create install directory if it doesn't exist
    if [ ! -d "\$INSTALL_DIR" ]; then
        mkdir -p "\$INSTALL_DIR" || error_exit "Failed to create install directory: \$INSTALL_DIR"
    fi
    
    # Download binary
    if curl -fsSL "\$download_url" -o "\$temp_file"; then
        # Make executable
        chmod +x "\$temp_file"
        
        # Move to install directory
        mv "\$temp_file" "\$INSTALL_DIR/crush" || error_exit "Failed to install Crush binary"
        
        print_success "Crush installed to \$INSTALL_DIR/crush"
        
        # Check if install dir is in PATH
        if [[ ":\$PATH:" != *":\$INSTALL_DIR:"* ]]; then
            print_warning "\$INSTALL_DIR is not in your PATH"
            print_info "Add the following to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
            echo ""
            echo "    export PATH=\"\\\$HOME/.local/bin:\\\$PATH\""
            echo ""
            # Temporarily add to PATH for this session
            export PATH="\$INSTALL_DIR:\$PATH"
        fi
        
        return 0
    else
        rm -f "\$temp_file" 2>/dev/null
        error_exit "Failed to download Crush binary from \$download_url"
    fi
}

# ----------------------------------------------------------------------------
# Main Installation Steps
# ----------------------------------------------------------------------------

print_header "CRUSH Configuration Installer"

# Step 1: Detect platform
print_info "Detecting platform..."
PLATFORM=\$(detect_platform)
print_success "Platform detected: \$PLATFORM"

# Step 2: Check if Crush is installed, install if not
print_info "Checking if Crush is installed..."
if command -v crush &> /dev/null; then
    CRUSH_VERSION=\$(crush --version 2>/dev/null || echo "unknown")
    print_success "Crush is already installed (version: \$CRUSH_VERSION)"
else
    print_warning "Crush is not installed"
    print_info "Installing Crush automatically..."
    install_crush "\$PLATFORM"
    
    # Verify installation
    if command -v crush &> /dev/null || [ -x "\$INSTALL_DIR/crush" ]; then
        print_success "Crush installed successfully"
    else
        error_exit "Crush installation failed"
    fi
fi

# Step 3: Create config directory
print_info "Creating config directory..."
if [ ! -d "\$CONFIG_DIR" ]; then
    mkdir -p "\$CONFIG_DIR" || error_exit "Failed to create config directory"
    print_success "Created \$CONFIG_DIR"
else
    print_success "Config directory already exists"
fi

# Step 4: Download configuration
print_info "Downloading configuration from \$BASE_URL/api/config..."
if curl -fsSL "\$BASE_URL/api/config" -o "\$CONFIG_FILE"; then
    print_success "Configuration downloaded to \$CONFIG_FILE"
else
    error_exit "Failed to download configuration"
fi

# Step 5: Clone or update Skills repository
print_info "Setting up Skills repository..."
if [ -d "\$SKILLS_DIR" ]; then
    print_info "Skills directory exists, updating..."
    cd "\$SKILLS_DIR"
    if git pull --quiet; then
        print_success "Skills repository updated"
    else
        print_warning "Failed to update Skills repository, continuing..."
    fi
    cd - > /dev/null
else
    print_info "Cloning Skills repository..."
    if git clone --quiet "\$SKILLS_REPO" "\$SKILLS_DIR"; then
        print_success "Skills repository cloned to \$SKILLS_DIR"
    else
        error_exit "Failed to clone Skills repository"
    fi
fi

# Step 6: Validate installation
print_info "Validating installation..."
VALIDATION_PASSED=true

# Check Crush binary
if command -v crush &> /dev/null || [ -x "\$INSTALL_DIR/crush" ]; then
    print_success "Crush binary is available"
else
    print_error "Crush binary not found"
    VALIDATION_PASSED=false
fi

if [ -f "\$CONFIG_FILE" ]; then
    print_success "Config file exists: \$CONFIG_FILE"
else
    print_error "Config file not found: \$CONFIG_FILE"
    VALIDATION_PASSED=false
fi

if [ -d "\$SKILLS_DIR" ]; then
    SKILLS_COUNT=\$(find "\$SKILLS_DIR" -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
    print_success "Skills directory exists: \$SKILLS_DIR"
else
    print_error "Skills directory not found: \$SKILLS_DIR"
    VALIDATION_PASSED=false
    SKILLS_COUNT=0
fi

if [ "\$VALIDATION_PASSED" = false ]; then
    error_exit "Installation validation failed"
fi

# ----------------------------------------------------------------------------
# Installation Summary
# ----------------------------------------------------------------------------
print_header "Installation Summary"

echo "  Crush binary:     \$(command -v crush || echo "\$INSTALL_DIR/crush")"
echo "  Config file:      \$CONFIG_FILE"
echo "  Skills directory: \$SKILLS_DIR"
echo "  Skills count:     \$SKILLS_COUNT"
echo ""

print_success "Installation completed successfully!"

# ----------------------------------------------------------------------------
# Next Steps
# ----------------------------------------------------------------------------
print_header "Next Steps"

echo "  1. Configure your API keys:"
echo "     export ANTHROPIC_API_KEY=your_key"
echo "     export OPENAI_API_KEY=your_key"
echo ""
echo "  2. Login to Crush:"
echo "     crush login"
echo ""
echo "  3. Start using Crush:"
echo "     crush"
echo ""
print_info "Documentation: \$DOCS_URL"
echo ""
`;
}
