/**
 * Unix (Linux/macOS) 安装脚本模板
 * 生成用于安装 CRUSH 配置的 bash 脚本
 */

/**
 * 生成 Unix 安装脚本
 * @param baseUrl - 配置服务器的基础 URL
 * @returns 完整的 bash 安装脚本
 */
export function generateUnixScript(baseUrl: string): string {
  return `#!/bin/bash
# ============================================================================
# CRUSH Configuration Installer for Unix (Linux/macOS)
# Generated by ${baseUrl}
# ============================================================================

set -e

# ----------------------------------------------------------------------------
# Color Definitions
# ----------------------------------------------------------------------------
RED='\\033[0;31m'
GREEN='\\033[0;32m'
BLUE='\\033[0;34m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
BASE_URL="${baseUrl}"
CONFIG_DIR="\$HOME/.config/crush"
CONFIG_FILE="\$CONFIG_DIR/crush.json"
SKILLS_DIR="\$CONFIG_DIR/skills"
SKILLS_REPO="https://github.com/anthropics/skills.git"
DOCS_URL="${baseUrl}"

# ----------------------------------------------------------------------------
# Output Functions
# ----------------------------------------------------------------------------
print_success() {
    echo -e "\${GREEN}✓ \$1\${NC}"
}

print_error() {
    echo -e "\${RED}✗ \$1\${NC}" >&2
}

print_info() {
    echo -e "\${BLUE}ℹ \$1\${NC}"
}

print_warning() {
    echo -e "\${YELLOW}⚠ \$1\${NC}"
}

print_header() {
    echo ""
    echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
    echo -e "\${BLUE}  \$1\${NC}"
    echo -e "\${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
    echo ""
}

# ----------------------------------------------------------------------------
# Error Handler
# ----------------------------------------------------------------------------
error_exit() {
    print_error "\$1"
    exit 1
}

# ----------------------------------------------------------------------------
# Main Installation Steps
# ----------------------------------------------------------------------------

print_header "CRUSH Configuration Installer"

# Step 1: Check if Crush is installed
print_info "Checking if Crush is installed..."
if ! command -v crush &> /dev/null; then
    print_error "Crush is not installed!"
    echo ""
    print_info "Please install Crush first:"
    echo "  • macOS: brew install charmbracelet/tap/crush"
    echo "  • Linux: See https://github.com/charmbracelet/crush#installation"
    echo ""
    exit 1
fi
print_success "Crush is installed"

# Step 2: Create config directory
print_info "Creating config directory..."
if [ ! -d "\$CONFIG_DIR" ]; then
    mkdir -p "\$CONFIG_DIR" || error_exit "Failed to create config directory"
    print_success "Created \$CONFIG_DIR"
else
    print_success "Config directory already exists"
fi

# Step 3: Download configuration
print_info "Downloading configuration from \$BASE_URL/api/config..."
if curl -fsSL "\$BASE_URL/api/config" -o "\$CONFIG_FILE"; then
    print_success "Configuration downloaded to \$CONFIG_FILE"
else
    error_exit "Failed to download configuration"
fi

# Step 4: Clone or update Skills repository
print_info "Setting up Skills repository..."
if [ -d "\$SKILLS_DIR" ]; then
    print_info "Skills directory exists, updating..."
    cd "\$SKILLS_DIR"
    if git pull --quiet; then
        print_success "Skills repository updated"
    else
        print_warning "Failed to update Skills repository, continuing..."
    fi
    cd - > /dev/null
else
    print_info "Cloning Skills repository..."
    if git clone --quiet "\$SKILLS_REPO" "\$SKILLS_DIR"; then
        print_success "Skills repository cloned to \$SKILLS_DIR"
    else
        error_exit "Failed to clone Skills repository"
    fi
fi

# Step 5: Validate installation
print_info "Validating installation..."
VALIDATION_PASSED=true

if [ -f "\$CONFIG_FILE" ]; then
    print_success "Config file exists: \$CONFIG_FILE"
else
    print_error "Config file not found: \$CONFIG_FILE"
    VALIDATION_PASSED=false
fi

if [ -d "\$SKILLS_DIR" ]; then
    SKILLS_COUNT=\$(find "\$SKILLS_DIR" -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
    print_success "Skills directory exists: \$SKILLS_DIR"
else
    print_error "Skills directory not found: \$SKILLS_DIR"
    VALIDATION_PASSED=false
    SKILLS_COUNT=0
fi

if [ "\$VALIDATION_PASSED" = false ]; then
    error_exit "Installation validation failed"
fi

# ----------------------------------------------------------------------------
# Installation Summary
# ----------------------------------------------------------------------------
print_header "Installation Summary"

echo "  Config file:     \$CONFIG_FILE"
echo "  Skills directory: \$SKILLS_DIR"
echo "  Skills count:     \$SKILLS_COUNT"
echo ""

print_success "Installation completed successfully!"

# ----------------------------------------------------------------------------
# Next Steps
# ----------------------------------------------------------------------------
print_header "Next Steps"

echo "  1. Configure your API keys:"
echo "     export ANTHROPIC_API_KEY=your_key"
echo "     export OPENAI_API_KEY=your_key"
echo ""
echo "  2. Login to Crush:"
echo "     crush login"
echo ""
echo "  3. Start using Crush:"
echo "     crush"
echo ""
print_info "Documentation: \$DOCS_URL"
echo ""
`;
}
