/**
 * Windows 安装脚本模板
 * 生成用于安装 CRUSH 及其配置的 PowerShell 脚本
 */

/**
 * 生成 Windows 安装脚本
 * @param baseUrl - 配置服务器的基础 URL
 * @returns 完整的 PowerShell 安装脚本
 */
export function generateWindowsScript(baseUrl: string): string {
  return `# ============================================================================
# CRUSH Configuration Installer for Windows (PowerShell)
# Generated by ${baseUrl}
# ============================================================================

$ErrorActionPreference = "Stop"

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
$BASE_URL = "${baseUrl}"
$CONFIG_DIR = "$env:LOCALAPPDATA\\crush"
$CONFIG_FILE = "$CONFIG_DIR\\crush.json"
$SKILLS_DIR = "$CONFIG_DIR\\skills"
$SKILLS_REPO = "https://github.com/anthropics/skills.git"
$DOCS_URL = "${baseUrl}"
$BIN_DIR = "$CONFIG_DIR\\bin"
$CRUSH_EXE = "$BIN_DIR\\crush.exe"

# ----------------------------------------------------------------------------
# Output Functions
# ----------------------------------------------------------------------------
function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Write-Error-Message {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ $Message" -ForegroundColor Blue
}

function Write-Warning-Message {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

function Write-Header {
    param([string]$Title)
    Write-Host ""
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
    Write-Host "  $Title" -ForegroundColor Blue
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
    Write-Host ""
}

# ----------------------------------------------------------------------------
# Error Handler
# ----------------------------------------------------------------------------
function Exit-WithError {
    param([string]$Message)
    Write-Error-Message $Message
    exit 1
}

# ----------------------------------------------------------------------------
# Install Crush Binary
# ----------------------------------------------------------------------------
function Install-Crush {
    $downloadUrl = "$BASE_URL/api/download/crush/windows/amd64"
    $tempFile = "$env:TEMP\\crush_$([System.Guid]::NewGuid().ToString()).exe"
    
    Write-Info "Downloading Crush binary..."
    
    # Create bin directory if it doesn't exist
    if (-not (Test-Path $BIN_DIR)) {
        try {
            New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
            Write-Success "Created $BIN_DIR"
        } catch {
            Exit-WithError "Failed to create bin directory: $_"
        }
    }
    
    # Download binary
    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile $tempFile -UseBasicParsing
        
        # Move to bin directory
        Move-Item -Path $tempFile -Destination $CRUSH_EXE -Force
        
        Write-Success "Crush installed to $CRUSH_EXE"
        
        # Add to PATH if not already there
        $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
        if ($userPath -notlike "*$BIN_DIR*") {
            Write-Info "Adding $BIN_DIR to user PATH..."
            $newPath = "$BIN_DIR;$userPath"
            [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
            $env:Path = "$BIN_DIR;$env:Path"
            Write-Success "Added to PATH (restart terminal for full effect)"
        }
        
        return $true
    } catch {
        if (Test-Path $tempFile) {
            Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
        }
        Exit-WithError "Failed to download Crush binary: $_"
    }
}

# ----------------------------------------------------------------------------
# Main Installation Steps
# ----------------------------------------------------------------------------

Write-Header "CRUSH Configuration Installer"

# Step 1: Check if Crush is installed, install if not
Write-Info "Checking if Crush is installed..."
$crushCommand = Get-Command crush -ErrorAction SilentlyContinue
if ($crushCommand) {
    try {
        $crushVersion = & crush --version 2>$null
        Write-Success "Crush is already installed (version: $crushVersion)"
    } catch {
        Write-Success "Crush is already installed"
    }
} elseif (Test-Path $CRUSH_EXE) {
    Write-Success "Crush is installed at $CRUSH_EXE"
    # Add to current session PATH
    $env:Path = "$BIN_DIR;$env:Path"
} else {
    Write-Warning-Message "Crush is not installed"
    Write-Info "Installing Crush automatically..."
    Install-Crush
    
    # Verify installation
    if (Test-Path $CRUSH_EXE) {
        Write-Success "Crush installed successfully"
    } else {
        Exit-WithError "Crush installation failed"
    }
}

# Step 2: Create config directory
Write-Info "Creating config directory..."
if (-not (Test-Path $CONFIG_DIR)) {
    try {
        New-Item -ItemType Directory -Path $CONFIG_DIR -Force | Out-Null
        Write-Success "Created $CONFIG_DIR"
    } catch {
        Exit-WithError "Failed to create config directory: $_"
    }
} else {
    Write-Success "Config directory already exists"
}

# Step 3: Download configuration
Write-Info "Downloading configuration from $BASE_URL/api/config..."
try {
    $configUrl = "$BASE_URL/api/config"
    Invoke-WebRequest -Uri $configUrl -OutFile $CONFIG_FILE -UseBasicParsing
    Write-Success "Configuration downloaded to $CONFIG_FILE"
} catch {
    Exit-WithError "Failed to download configuration: $_"
}

# Step 4: Clone or update Skills repository
Write-Info "Setting up Skills repository..."
if (Test-Path $SKILLS_DIR) {
    Write-Info "Skills directory exists, updating..."
    try {
        Push-Location $SKILLS_DIR
        git pull --quiet 2>$null
        Pop-Location
        Write-Success "Skills repository updated"
    } catch {
        Pop-Location
        Write-Warning-Message "Failed to update Skills repository, continuing..."
    }
} else {
    Write-Info "Cloning Skills repository..."
    try {
        git clone --quiet $SKILLS_REPO $SKILLS_DIR 2>$null
        Write-Success "Skills repository cloned to $SKILLS_DIR"
    } catch {
        Exit-WithError "Failed to clone Skills repository: $_"
    }
}

# Step 5: Validate installation
Write-Info "Validating installation..."
$validationPassed = $true

# Check Crush binary
$crushAvailable = (Get-Command crush -ErrorAction SilentlyContinue) -or (Test-Path $CRUSH_EXE)
if ($crushAvailable) {
    Write-Success "Crush binary is available"
} else {
    Write-Error-Message "Crush binary not found"
    $validationPassed = $false
}

if (Test-Path $CONFIG_FILE) {
    Write-Success "Config file exists: $CONFIG_FILE"
} else {
    Write-Error-Message "Config file not found: $CONFIG_FILE"
    $validationPassed = $false
}

if (Test-Path $SKILLS_DIR) {
    $skillsCount = (Get-ChildItem -Path $SKILLS_DIR -Recurse -Filter "SKILL.md" -ErrorAction SilentlyContinue | Measure-Object).Count
    Write-Success "Skills directory exists: $SKILLS_DIR"
} else {
    Write-Error-Message "Skills directory not found: $SKILLS_DIR"
    $validationPassed = $false
    $skillsCount = 0
}

if (-not $validationPassed) {
    Exit-WithError "Installation validation failed"
}

# ----------------------------------------------------------------------------
# Installation Summary
# ----------------------------------------------------------------------------
Write-Header "Installation Summary"

$crushPath = if (Get-Command crush -ErrorAction SilentlyContinue) { (Get-Command crush).Source } else { $CRUSH_EXE }
Write-Host "  Crush binary:     $crushPath"
Write-Host "  Config file:      $CONFIG_FILE"
Write-Host "  Skills directory: $SKILLS_DIR"
Write-Host "  Skills count:     $skillsCount"
Write-Host ""

Write-Success "Installation completed successfully!"

# ----------------------------------------------------------------------------
# Next Steps
# ----------------------------------------------------------------------------
Write-Header "Next Steps"

Write-Host "  1. Configure your API keys:"
Write-Host '     $env:ANTHROPIC_API_KEY = "your_key"'
Write-Host '     $env:OPENAI_API_KEY = "your_key"'
Write-Host ""
Write-Host "  2. Login to Crush:"
Write-Host "     crush login"
Write-Host ""
Write-Host "  3. Start using Crush:"
Write-Host "     crush"
Write-Host ""
Write-Info "Documentation: $DOCS_URL"
Write-Host ""
`;
}
