/**
 * Windows 安装脚本模板
 * 生成用于安装 CRUSH 配置的 PowerShell 脚本
 */

/**
 * 生成 Windows 安装脚本
 * @param baseUrl - 配置服务器的基础 URL
 * @returns 完整的 PowerShell 安装脚本
 */
export function generateWindowsScript(baseUrl: string): string {
  return `# ============================================================================
# CRUSH Configuration Installer for Windows (PowerShell)
# Generated by ${baseUrl}
# ============================================================================

$ErrorActionPreference = "Stop"

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
$BASE_URL = "${baseUrl}"
$CONFIG_DIR = "$env:LOCALAPPDATA\\crush"
$CONFIG_FILE = "$CONFIG_DIR\\crush.json"
$SKILLS_DIR = "$CONFIG_DIR\\skills"
$SKILLS_REPO = "https://github.com/anthropics/skills.git"
$DOCS_URL = "${baseUrl}"

# ----------------------------------------------------------------------------
# Output Functions
# ----------------------------------------------------------------------------
function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Write-Error-Message {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ $Message" -ForegroundColor Blue
}

function Write-Warning-Message {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

function Write-Header {
    param([string]$Title)
    Write-Host ""
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
    Write-Host "  $Title" -ForegroundColor Blue
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
    Write-Host ""
}

# ----------------------------------------------------------------------------
# Error Handler
# ----------------------------------------------------------------------------
function Exit-WithError {
    param([string]$Message)
    Write-Error-Message $Message
    exit 1
}

# ----------------------------------------------------------------------------
# Main Installation Steps
# ----------------------------------------------------------------------------

Write-Header "CRUSH Configuration Installer"

# Step 1: Check if Crush is installed
Write-Info "Checking if Crush is installed..."
$crushCommand = Get-Command crush -ErrorAction SilentlyContinue
if (-not $crushCommand) {
    Write-Error-Message "Crush is not installed!"
    Write-Host ""
    Write-Info "Please install Crush first:"
    Write-Host "  • Windows: scoop install charmbracelet/tap/crush"
    Write-Host "  • Or see: https://github.com/charmbracelet/crush#installation"
    Write-Host ""
    exit 1
}
Write-Success "Crush is installed"

# Step 2: Create config directory
Write-Info "Creating config directory..."
if (-not (Test-Path $CONFIG_DIR)) {
    try {
        New-Item -ItemType Directory -Path $CONFIG_DIR -Force | Out-Null
        Write-Success "Created $CONFIG_DIR"
    } catch {
        Exit-WithError "Failed to create config directory: $_"
    }
} else {
    Write-Success "Config directory already exists"
}

# Step 3: Download configuration
Write-Info "Downloading configuration from $BASE_URL/api/config..."
try {
    $configUrl = "$BASE_URL/api/config"
    Invoke-WebRequest -Uri $configUrl -OutFile $CONFIG_FILE -UseBasicParsing
    Write-Success "Configuration downloaded to $CONFIG_FILE"
} catch {
    Exit-WithError "Failed to download configuration: $_"
}

# Step 4: Clone or update Skills repository
Write-Info "Setting up Skills repository..."
if (Test-Path $SKILLS_DIR) {
    Write-Info "Skills directory exists, updating..."
    try {
        Push-Location $SKILLS_DIR
        git pull --quiet 2>$null
        Pop-Location
        Write-Success "Skills repository updated"
    } catch {
        Pop-Location
        Write-Warning-Message "Failed to update Skills repository, continuing..."
    }
} else {
    Write-Info "Cloning Skills repository..."
    try {
        git clone --quiet $SKILLS_REPO $SKILLS_DIR 2>$null
        Write-Success "Skills repository cloned to $SKILLS_DIR"
    } catch {
        Exit-WithError "Failed to clone Skills repository: $_"
    }
}

# Step 5: Validate installation
Write-Info "Validating installation..."
$validationPassed = $true

if (Test-Path $CONFIG_FILE) {
    Write-Success "Config file exists: $CONFIG_FILE"
} else {
    Write-Error-Message "Config file not found: $CONFIG_FILE"
    $validationPassed = $false
}

if (Test-Path $SKILLS_DIR) {
    $skillsCount = (Get-ChildItem -Path $SKILLS_DIR -Recurse -Filter "SKILL.md" -ErrorAction SilentlyContinue | Measure-Object).Count
    Write-Success "Skills directory exists: $SKILLS_DIR"
} else {
    Write-Error-Message "Skills directory not found: $SKILLS_DIR"
    $validationPassed = $false
    $skillsCount = 0
}

if (-not $validationPassed) {
    Exit-WithError "Installation validation failed"
}

# ----------------------------------------------------------------------------
# Installation Summary
# ----------------------------------------------------------------------------
Write-Header "Installation Summary"

Write-Host "  Config file:      $CONFIG_FILE"
Write-Host "  Skills directory: $SKILLS_DIR"
Write-Host "  Skills count:     $skillsCount"
Write-Host ""

Write-Success "Installation completed successfully!"

# ----------------------------------------------------------------------------
# Next Steps
# ----------------------------------------------------------------------------
Write-Header "Next Steps"

Write-Host "  1. Configure your API keys:"
Write-Host '     $env:ANTHROPIC_API_KEY = "your_key"'
Write-Host '     $env:OPENAI_API_KEY = "your_key"'
Write-Host ""
Write-Host "  2. Login to Crush:"
Write-Host "     crush login"
Write-Host ""
Write-Host "  3. Start using Crush:"
Write-Host "     crush"
Write-Host ""
Write-Info "Documentation: $DOCS_URL"
Write-Host ""
`;
}
